// priority: 0

console.info('Hiding things from JEI...')

JEIEvents.hideItems(event => {
	event.hide('mysticalagriculture:electrum_essence')
	event.hide('mysticalagriculture:electrum_seeds')
	event.hide('mysticalagriculture:invar_essence')
	event.hide('mysticalagriculture:invar_seeds')
	event.hide('mysticalagriculture:platinum_essence')
	event.hide('mysticalagriculture:platinum_seeds')
	event.hide('mysticalagriculture:rubber_essence')
	event.hide('mysticalagriculture:rubber_seeds')
	event.hide('mysticalagriculture:saltpeter_essence')
	event.hide('mysticalagriculture:saltpeter_seeds')
	event.hide('mysticalagriculture:apatite_essence')
	event.hide('mysticalagriculture:apatite_seeds')
	event.hide('mysticalagriculture:constantan_essence')
	event.hide('mysticalagriculture:constantan_seeds')
	event.hide('mysticalagriculture:mithril_essence')
	event.hide('mysticalagriculture:mithril_seeds')
	event.hide('mysticalagriculture:tungsten_essence')
	event.hide('mysticalagriculture:tungsten_seeds')
	event.hide('mysticalagriculture:titanium_essence')
	event.hide('mysticalagriculture:titanium_seeds')
	event.hide('mysticalagriculture:chrome_essence')
	event.hide('mysticalagriculture:chrome_seeds')
	event.hide('mysticalagriculture:iridium_essence')
	event.hide('mysticalagriculture:iridium_seeds')
	event.hide('mysticalagriculture:graphite_essence')
	event.hide('mysticalagriculture:graphite_seeds')
	event.hide('avaritia:neutronium_compressor')
	event.hide('avaritia:extreme_crafting_table')
	event.hide('avaritia:iron_singularity')
	event.hide('avaritia:golden_singularity')
	event.hide('avaritia:lapis_singularity')
	event.hide('avaritia:redstone_singularity')
	event.hide('avaritia:nether_quartz_singularity')
	event.hide('avaritia:diamond_singularity')
	event.hide('avaritia:emerald_singularity')
})
