
#General settings
[general]
	#Use config instead of datapack
	use_config = true

	#List settings
	#Syntax: ["modid:block|weight"]
	#Example: ["minecraft:stone|2","minecraft:dirt|1"]
	#Forge tags are supported
	[general.lists]
		#Cobble gen
		block_list_cobble = ["minecraft:cobblestone|60", "minecraft:coal_ore|25", "minecraft:copper_ore|20", "minecraft:iron_ore|20", "minecraft:redstone_ore|20", "minecraft:lapis_ore|20", "minecraft:emerald_ore|5", "minecraft:gold_ore|10", "minecraft:diamond_ore|5", "create:zinc_ore|20", "mekanism:tin_ore|20", "mekanism:osmium_ore|20", "mekanism:uranium_ore|10", "mekanism:fluorite_ore|10", "mekanism:lead_ore|20", "powah:uraninite_ore_poor|10", "powah:uraninite_ore|5", "powah:uraninite_ore_dense|1"]
		#Stone gen
		block_list_stone = ["minecraft:stone|30", "minecraft:granite|10", "minecraft:diorite|10", "minecraft:andesite|10", "create:limestone|10", "quark:limestone|10", "quark:shale|10", "quark:jasper|10", "minecraft:amethyst_block|5", "minecraft:calcite|5"]
		#Basalt gen
		block_list_basalt = ["minecraft:basalt|60", "minecraft:blackstone|60", "minecraft:netherrack|60", "minecraft:soul_sand|30", "minecraft:soul_soil|30", "mysticalagriculture:soulstone|30", "mysticalagriculture:soulium_ore|10", "minecraft:nether_quartz_ore|30", "mysticalagradditions:nether_inferium_ore|20", "mysticalagradditions:nether_prosperity_ore|20", "tconstruct:cobalt_ore|20", "rftoolsbase:dimensionalshard_nether|5", "minecraft:glowstone|30", "minecraft:nether_gold_ore|30", "minecraft:ancient_debris|1"]

		#Custom settings
		[general.lists.custom]
			#Custom generators
			#Syntax: [gen]
			#Gen: [type, block, list]
			#Type: cobblestone, stone
			#Block: resource location of the block below the generated block
			#List: see List settings
			#Examples:
			#custom_generators = [
			#   ["cobblestone", "minecraft:diamond_block", ["minecraft:diamond_block"]],
			#   ["cobblestone", "minecraft:dirt", ["forge:dirt"]],
			#   ["cobblestone", "minecraft:white_wool", ["minecraft:wool"]]]
			custom_generators = [["cobblestone", "minecraft:deepslate", ["minecraft:deepslate|60", "minecraft:tuff|40", "minecraft:deepslate_coal_ore|25", "minecraft:deepslate_copper_ore|20", "minecraft:deepslate_iron_ore|20", "minecraft:deepslate_redstone_ore|20", "minecraft:deepslate_lapis_ore|20", "minecraft:deepslate_emerald_ore|5", "minecraft:deepslate_gold_ore|10", "minecraft:deepslate_diamond_ore|5", "create:deepslate_zinc_ore|20", "mekanism:deepslate_tin_ore|20", "mekanism:deepslate_osmium_ore|20", "mekanism:deepslate_uranium_ore|10", "mekanism:deepslate_fluorite_ore|10", "mekanism:deepslate_lead_ore|20", "powah:deepslate_uraninite_ore_poor|10", "powah:deepslate_uraninite_ore|5", "powah:deepslate_uraninite_ore_dense|1"]], ["stone", "minecraft:end_stone", ["minecraft:end_stone|60", "mysticalagradditions:end_prosperity_ore|10", "mysticalagradditions:end_inferium_ore|10", "rftoolsbase:dimensionalshard_end|5"]]]

