
[General]
	#The number of item stacks held in a basic unit of storage.
	#1x1 drawers hold 8 units, 1x2 drawers hold 4 units, 2x2 drawers hold 2 units.
	#Half-depth drawers hold half those amounts.
	baseStackStorage = 4
	#Controller range defines how far away a drawer can be connected
	#on X, Y, or Z planes.  The default value of 50 gives the controller a very
	#large range, but not beyond the chunk load distance.
	#Range: 1 ~ 75
	controllerRange = 50
	enableUI = true
	enableSidedInput = true
	enableSidedOutput = true
	enableItemConversion = true
	enableExtraCompactingRules = true
	debugTrace = false
	#List of rules in format "domain:item1, domain:item2, n".
	#Creates a compacting drawer rule to convert 1 of item1 into n of item2.
	compactingRules = [
		"minecraft:clay, minecraft:clay_ball, 4",
		"minecraft:raw_iron, exnihilosequentia:iron_pieces, 4",
		"minecraft:raw_gold, exnihilosequentia:gold_pieces, 4",
		"minecraft:raw_copper, exnihilosequentia:copper_pieces, 4",
		"exnihilosequentia:raw_nickel, exnihilosequentia:nickel_pieces, 4",
		"exnihilosequentia:raw_aluminum, exnihilosequentia:aluminum_pieces, 4",
		"exnihilosequentia:raw_zinc, exnihilosequentia:zinc_pieces, 4",
		"exnihilosequentia:raw_lead, exnihilosequentia:lead_pieces, 4",
		"mekanism:raw_osmium, exnihilomekanism:osmium_pieces, 4",
		"exnihilosequentia:raw_silver, exnihilosequentia:silver_pieces, 4",
		"exnihilosequentia:raw_platinum, exnihilosequentia:platinum_pieces, 4",
		"exnihilosequentia:raw_tin, exnihilosequentia:tin_pieces, 4",
		"exnihilosequentia:raw_uranium, exnihilosequentia:uranium_pieces, 4"
	]

[StorageUpgrades]
	#Storage upgrades multiply storage capacity by the given amount.
	#When multiple storage upgrades are used together, their multipliers are added before being applied.
	level1Mult = 2
	level2Mult = 4
	level3Mult = 8
	level4Mult = 16
	level5Mult = 32

[Integration]
	#When true, shows quantity as NxS + R (by stack size) rather than count
	wailaStackRemainder = true
	#When true, does not show current quantities unless quantify key was used
	wailaRespectQuantifyKey = false

